name: Create a new KSE release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:

  launcher:
    name: Build KSE launcher
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install nim mingw-w64
      - name: Build
        run: nim -d:mingw --cpu:amd64 -d:release --app:gui --opt:size --out:kse-launcher.exe c kse_launcher.nim
        working-directory: kse/res
      - name: Shrink executable
        run: strip kse/res/kse-launcher.exe
      - name: Store artifacts for release
        uses: actions/upload-artifact@v4
        with:
          name: kse-launcher
          path: kse/res/kse-launcher.exe

  windows:
    name: Create artifacts on Windows
    needs: [launcher]
    runs-on: windows-2019
    steps:
      - name: Disable automatic EOL conversions
        run: git config --global core.autocrlf false
      - name: Install required software packages
        run: choco install reshack
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: actions/download-artifact@v4.1.7
        with:
          name: kse-launcher
          path: kse/res
      - name: Build with Gradle
        run: .\gradlew.bat test zip innosetup
        working-directory: kse
      - name: Store artifacts for release
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            kse/build/launcher/kse.exe
      - name: Store artifacts for release
        uses: actions/upload-artifact@v4
        with:
          # use second step with same artifact name in order to avoid sub-folders
          name: windows-artifacts
          path: |
            kse/build/distributions/kse-*.zip
            kse/build/distributions/kse-*-setup-no-jre.exe

  windows-with-jre:
    name: Create a Windows installer with included JRE
    needs: [launcher]
    runs-on: windows-2019
    steps:
      - name: Disable automatic EOL conversions
        run: git config --global core.autocrlf false
      - name: Install required software packages
        run: choco install reshack
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: actions/download-artifact@v4.1.7
        with:
          name: kse-launcher
          path: kse/res
      - name: Build with Gradle
        run: .\gradlew.bat test innosetup
        working-directory: kse
      - name: Store artifacts for release
        uses: actions/upload-artifact@v4
        with:
          name: windows-with-jre-artifact
          path: kse/build/distributions/kse-*-setup.exe

  release:
    needs: [windows, windows-with-jre]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          name: windows-artifacts
      - uses: actions/download-artifact@v4.1.7
        with:
          name: windows-with-jre-artifact
      - name: Create a release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          name: "KSE Release ${{ github.ref_name }}"
          body: "Release Notes are available here: [Release Notes](https://keystore-explorer.org/releases.html)"
          files: |
            kse-*.zip
            kse-*-setup.exe
            kse-*-setup-no-jre.exe
          token: ${{ secrets.github_token }}
